### ISSUE TITLE
Data fixes Sept 2 2019

### ISSUE THREAD

**Issue by kmel90** [alan412/CheckMeIn#19]
Hi Alan,

Going through the various sources of data prior to membership and found some fixes for the checkmein system. For the merge with fixes, the 'merge with x' , the x is the correct number.

I am going to assign barcodes from within Salesforce going forward. This will NOT change the existing barcodes in the system (if all goes well). 

Is there a way to give you a file with a list of new display names and barcodes to import into the system periodically during membership?

Alexander G | 100334 | change to Alex G
Naren T | 100312 | merge with 100397
Rowan S | 100059 | change from Kira S
Sashank S | 100526 | fix spelling to Shashank S
Shreyas T | 100315 | merge with 100396
Sudiksha T | 100314 | merge with 100394
Visweswari T | 100313 | merge with 100395
Jahnvi P | 100521 | merge with 100354

**Comment by alan412** [comment]
Great news!   I have added a bulk add feature that will take in a CSV from a SalesForce report and will replace the name (if the barcode id already exists) or add it (if the barcode id doesn't exist.)

I need to think about how to do the merging without breaking things.   For now, pulling in the new one from Sales Force will cause everything to work off the new id (even though the old id will still be sitting around.)
