### ISSUE TITLE
To make life easier on navigation

### ISSUE THREAD

**Issue by lwhipker** [alan412/CheckMeIn#50]
Could we get a way "back" to the main menu or to the previous screen or another navigational place on every page in the app?  Often my only way out is to close the app and get back in.

Thank you!!!!

**Comment by alan412** [comment]
Secret tip:   From just about everywhere in the app, if you click on the
logo it takes you back to your main screen.   Let me know if you find a
place it doesn't work.

--Alan

**Comment by lwhipker** [comment]
About 10 places today...  :)
I tried that trick and it did work a few places.

**Comment by lwhipker** [comment]
I was going through the entire CheckMeIn app with Ganesh as a new keyholder today. Several places we came to a deadend. Looked at teams, and "Oops"  - actually, followed almost every trail. I didn't mark which ones didn't work but did try every time

**Comment by lwhipker** [comment]
This page, for example, is what nudged me to comment just now.
https://tfi.checkmein.site/reports/

**Comment by alan412** [comment]
It turns out it only happened in one place (the main checkin screen).   I changed it to happen now everywhere.
