### ISSUE TITLE
what are my options for the SQL contains column names ? 

### ISSUE THREAD

**Issue by MariaHunter3459** [alan412/CheckMeIn#61]
How are we meant to know all of the options for the contains (column 1, column 2, ... , etc)? Could this list be part of the custom report interface?

**Comment by alan412** [comment]
I made a new custom report that will show that:
https://tfi.checkmein.site/reports/savedCustom?report_id=21

**Comment by alan412** [comment]
This is the SQL code for that report:
```
WITH tables AS (SELECT name tableName, sql 
FROM sqlite_master WHERE type = 'table' AND tableName NOT LIKE 'sqlite_%')
SELECT tableName, fields.name, fields.type
FROM tables CROSS JOIN pragma_table_info(tables.tableName) fields
ORDER BY tableName;
```
