### ISSUE TITLE
Duplicate/Wrong Name

### ISSUE THREAD

**Issue by kmel90** [alan412/CheckMeIn#8]
100311 | Visweswari T | 1
100313 | Visweswari T | 1

Trying to figure out the missing numbers and I screwed up.
10311 should be Clark I but somehow I typed in Visweswari T by mistake.

Any way to fix this?
Karen

**Comment by kmel90** [comment]
Now I know why it didn't work the first time, I missed a zero.
10311 | Clark I
Should be 100311.

**Comment by alan412** [comment]
I have fixed these manually.  Need to think about how to make an interface
to fix things like this.

**Comment by kmel90** [comment]
Need a display name change  Yagya G needs to change to Yagya K #100464

**Comment by alan412** [comment]
done.
